### ISSUE TITLE
Pygmy logo for contribution

### ISSUE THREAD

**Issue by batarian71** [amitt001/pygmy#10]
Hi, @amitt001 . I designed a logo for your webapp. I hope you like logo. If there's anything you want, please tell me. 

![py](https://user-images.githubusercontent.com/36008612/39628189-e6cafef6-4fb0-11e8-87e4-d6de6d54fe70.jpg)

**Comment by amitt001** [comment]
Hi @batarian71 thank you for designing the logo. They all look good. Out of these three, I think the middle one suits most with the application of the website.

I would prefer an SVG logo over PNG or JPG because of its sharpness across different screen sizes and lighter size which will help the web app load a little faster. 

Would you be able to create an SVG logo for the middle one? Once you are done please open a PR.

The logo should go here https://github.com/amitt001/pygmy/tree/master/src/pyui/static in a 'logo' directory. I'd be willing to add your name to the project README for logo contribution. Meanwhile, I will modify the page to support logo.

**Comment by batarian71** [comment]
Thank you @amitt001 . I sent pr. I added svg version.

**Comment by amitt001** [comment]
Hi @batarian71 I have added your name in https://github.com/amitt001/pygmy#contributions section.

While I am fine with the current logo but I think the link part of the logo is not easily visible. What I mean is the black and green links somehow mixes with the other part of 'P'. I think fading out the line in P or using different color might make it better. What do you think?

**Comment by batarian71** [comment]
Of course, How do these look? in the first logo ; I placed the letter P in the back. Thus, The link symbol has become evident. 

![py](https://user-images.githubusercontent.com/36008612/39876566-37645cac-547c-11e8-9cb7-82089effe15f.jpg)

**Comment by amitt001** [comment]
@batarian71 The first one looks good. Please open a PR. I would also like to keep the current logos just in case. So let them be there and put these with logov2 or some name.

**Comment by batarian71** [comment]
i sent a pr. https://github.com/amitt001/pygmy/pull/13

editablefiles: https://drive.google.com/drive/folders/1TrU6Nsc7koTKQf2Z22Vgte-90uLmuaWe

**Comment by amitt001** [comment]
Added logo to website. Closing this.
