### ISSUE TITLE
Support longer custom links and give proper error if its longer than allowed 

### ISSUE THREAD

**Issue by alexgleason** [amitt001/pygmy#9]
Hi, thanks for providing this!

I made one link and it worked. Then I tried making a second link and it didn't. It sent back a 500.

Here's my link: https://deckbox.org/sets/1977804

I tried with the name `deckbox` and `mtgdeck`, no dice.

**Comment by amitt001** [comment]
@alexgleason I see some CPU spikes on the server. I will check the logs.
The service is working now. Here is your short link for the above URL: http://pygy.co/e1

**Comment by amitt001** [comment]
@alexgleason initially I interpreted this issue wrong. The issue was with the custom URLs. In the app, max custom URL length was 8 but in DB it was only 6 so this error. I fixed it by increasing the max allowed length of custom URLs to 10 on both app and DB. Your links should work now.

Thanks for reporting.

**Comment by amitt001** [comment]
It's already fixed. Closing the ticket.
